# vim: set ft=ruby :

Vagrant.configure('2') do |config|

  config.vm.box = 'bento/debian-7.8'

  config.vm.hostname = 'zend-vagrant'
  config.vm.network :private_network, ip: '192.168.60.100'
  config.vm.network "forwarded_port", guest: 1080, host: 2080 
  config.vm.network "forwarded_port", guest: 1025, host: 2025 
 
  config.vm.synced_folder '~', '/home/master'
  config.vm.synced_folder '../', '/home/vagrant/source'
  
  config.vm.provider :virtualbox do |vb|
    vb.customize ['modifyvm', :id, '--cpus', '1', '--memory', 2048]
  end
 
  config.vm.provision :ansible do |ansible|
    ansible.playbook = 'ansible/playbook.yml'
  end

end
